on: [push, pull_request]
name: Test, build, publish
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        args: install
    - name: Test
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        args: test
    - name: Build
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        args: build
    - name: Has tag
      uses: actions/bin/filter@8075e145e58d8ad0392cb3ff6c30a00fa07dcf8d
      with:
        args: tag v*
    - name: Publish
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish --access public
